# GET http://localhost:5000/test
# content-type: application/json

POST https://4792919a3643.ngrok.io/text-data HTTP/1.1
content-type: application/json

{
    "url": "https://www.youtube.com/watch?v=hQzlNlHcN0A",
    "per_frame": 1
}